- .github/ISSUE_TEMPLATE/a11y_investigation.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/spike.md
- .github/ISSUE_TEMPLATE/story.md
- .github/ISSUE_TEMPLATE/task.md
PPDSC-2042 #105 
**What**
1. Background - now that we are open source we would like to try using github for issue tracking instead of jria 
2. What did you do - copied templates from jira and concerted to markdown
3. What does the reviewers should expect - please review templates, and suggested improvements welcome
> feat(PPDSC-2042): update issue templates

- site/pages/about/contact-us.tsx
PPDSC-2019
**What**
Replaced contact us form with new design
**Before**
**After:**
**Who should review this PR**
**How to test**
> feat(PPDSC-2019): Replace contact us form

- src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
- src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
- src/audio-player-composable/__tests__/audio-player-composable.test.tsx
- src/audio-player-composable/__tests__/utils.test.tsx
- src/audio-player-composable/audio-functions.ts
- src/audio-player-composable/audio-player-composable.tsx
- src/audio-player-composable/components/audio-element.tsx
- src/audio-player-composable/components/play-pause-button/play-pause-button.tsx
- src/audio-player-composable/components/play-pause-button/types.ts
- src/audio-player-composable/components/seek-bar/defaults.ts
- src/audio-player-composable/components/seek-bar/seek-bar.tsx
- src/audio-player-composable/components/seek-bar/style-presets.ts
- src/audio-player-composable/components/seek-bar/types.ts
- src/audio-player-composable/components/seek-bar/utils.ts
- src/audio-player-composable/context.tsx
- src/audio-player-composable/types.ts
- src/audio-player-composable/utils.ts
- src/theme/__tests__/__snapshots__/theme.test.ts.snap
PPDSC-2031
- Separate the seekBar to an independent component
- Add stories for default and overrides
I've not implemented the layout as it makes more sense to apply grid once we have the controls.
**Before**
**After:**
**Who should review this PR**
**How to test**
> feat(PPDSC-2031): audio player seekbar

- .github/PULL_REQUEST_TEMPLATE.md
- docs/testing.md
[PPDSC-2046](https://nidigitalsolutions.jira.com/browse/PPDSC-2046)
**What**
The PR template was a bit outdated.
Updated the PR template
- For the current changes I've investigated a bunch of other open source design systems PR template but most of them contained the same information that we currently have or less. So there are no new rules/checkboxes added to our template.
- I've removed some of our current checkboxes after a talk with @mutebg . Please review the changes and if you think we should bring back something or we should add a new one feel free to leave a comment. I am still new to the project so it's possible that I don't understand the reasoning behind each checkbox.
**I have …
> chore(PPDSC-2046): review PR template

- .circleci/config.yml
- Makefile
PPDSC-2007
**What**
Fixing version parameter drill
Improving the regex, on regexr I was getting an error around the `*` I've removed. Altho has worked fine even with it.
**Before:**
**After:**
> chore(PPDSC-2007): GitFlow to GitHub Flow: Fixing version parameter drill

- README.md
- package.json
PPDSC-2007
**What**
Rolling back to 5.4.0 in package JSON, so I can try again to release (5.4.1 HAS NOT been released to npm or to any environment)
**Before:**
**After:**
> Chore/ppdsc 2007 rolling back package.json version

- eks/values/product-platforms-values-dev.yaml
- eks/values/product-platforms-values-prod.yaml
PPDSC-2198
**What**
1. Dev and Prod doc sites are down due to SSL Certs being out of date
2. Updated the SSL Certs ARNs provided by Cloud Engineering
3. I believe the only way to see this work is a full deploy
**Before:**
**After:**
> fix(PPDSC-2198): update SSL Cert ARNs

- .circleci/config.yml
PPDSC-2220
**What**
Added more required steps before enabling "i_have_merged_applitools" approval step.
**Before:**
**After:**
> feat(PPDSC-2220): improve main branch protection in ci

- site/pages/index.tsx
- src/audio-player/__tests__/audio-player.stories.tsx
PPDSC-000
Testing with Pancho DEV enviroment and PROD issue
**Before:**
**After:**
> chore(PPDSC-000): Testing with Pancho DEV enviroment and PROD issue

- .circleci/config.yml
- site/pages/index.tsx
- src/audio-player/__tests__/audio-player.stories.tsx
Reverts newscorp-ghfb/newskit#251
> Revert "chore(PPDSC-000): Testing with Pancho DEV enviroment and PROD issue"

- .circleci/config.yml
PPDSC-2277
**What**
Passed context to every Job so slack notify could access to the slack token
**Before:**
**After:**
> fix(PPDSC-2277): CircleCI not sending message on pipeline failures

- .circleci/config.yml
Reverts newscorp-ghfb/newskit#260
> Revert "chore(PPDSC-000): add export DOCKER_TAG to the eks_flux_deploy CircleCI job"

- src/audio-player-composable/__tests__/audio-player-composable.stories.tsx
[PPDSC-2311](https://nidigitalsolutions.jira.com/browse/PPDSC-2311)
**What**
1. Background - audio player initial props tests keep being aborted
2. What did you do - skipped tests
3. What does the reviewers should expect - tests should not run
**Before:**
**After:**
> feat(PPDSC-2311): temporarily skip aborted tests

- README_COMPONENTS.md
PPDSC-2394
**What**
1. Background - why this is needed - docs were out of date
2. What did you do - updated docs 
3. What does the reviewers should expect - docs to be correct for v6
> docs(PPDSC-2394): update readme

- eks/manifests/ingress.yaml
PPDSC-2379
**What**
Updated k8 ingress,
Checked with Tim and Jakub if everything was ok
**Before:**
**After:**
> chore(PPDSC-2379): update k8 ingress

- site/components/illustrations/theme/transition-presets/predefined-transition-presets/maxheightchange.tsx
- site/pages/theme/presets/transition-presets.tsx
PPDSC-2357
**What**
1. Added maxHeightChange transition presets to table - http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2357-update-transition-preset-doc/theme/presets/transition-presets/#predefined-transition-presets
- [] The feature's functionality is working as expected on Chrome, Firefox, Safari and Edge
**Before:**
**After:**
URL: http://ncu-newskit-docs.s3-website-eu-west-1.amazonaws.com/ppdsc-2357-update-transition-preset-doc/theme/presets/transition-presets/#predefined-transition-presets
> docs(PPDSC-2357):  Update on transition presets doc table

- src/__tests__/__snapshots__/index.test.ts.snap
- src/utils/index.ts
PPDSC-2405
Dow Jones want to add their own style presets to control components (rather than using overrides). Exporting withOwnTheme will allow them to do this. For teams working on a custom components or potential contributions, it will allow them to work in a way that is more aligned with how we are building components. 
Link to Slack conversation: [Slack message from Chuy Pacheco in #newskit-dowjones-support](https://newsuktechnology.slack.com/archives/C024ZGQ2W8K/p1661785280144089) 
We performed a spike ([PPDSC-2405: Investigate whether to export withOwnTheme](https://nidigitalsolutions.jira.com/wiki/spaces/NPP/pages/4121297693/PPDSC-2405+Investigate+whether+to+export+withOwnTheme)) and decided that this is the right thing to do for DJ
This function is tested in every component's unit …
> feat(PPDSC-2405): export withOwnTheme

- cypress/site/visual/darktheme-snapshots.spec.js
- cypress/site/visual/fullpage-snapshots.spec.js
[PPDSC-2488](https://nidigitalsolutions.jira.com/browse/PPDSC-2488)
**What**
1. Background - cypress failing in docsite visual tests
2. What did you do - resolve test issues and only allow job to pass if all failures are visual test failures
3. What does the reviewers should expect - pipeline should fail if tests do not run, updated baselines for audio player doc site test
**Before:**
**After:**
> fix(PPDSC-2488): fix failing cypress tests

- .circleci/config.yml
PPDSC-2471
**What**
Following to #427 
Updating `eks_flux_deploy` step to take advantage of the newly tagged builds. 
This should be merged in order to be tested on the `main` pipeline.
If this works as expected there will be one more PR which removed the manual Approve `approve_publish_docs_&_storybook` step.
**Before:**
**After:**
> ci(PPDSC-2471): update DOCKER_TAG in eks_flux_deploy

- .circleci/config.yml
PPDSC-2471
**What**
1. Background - There is a manual approve step `approve_publish_docs_&_storybook` which is now working properly and we have to remove it so the docs and storybook deployment happens automatically on every push to `main`
2. What did you do - updated the `config.yml` file to remove the approval step
3. What does the reviewers should expect - When this PR is merged this step should be removed and the pipeline should automatically deploy docs and storybook to prod.
**Before:**
**After:**
> ci(PPDSC-2471): release website with every merge to main 

- src/tabs/__tests__/tabs.stories.tsx
[PPDSC-2513](https://nidigitalsolutions.jira.com/browse/PPDSC-2513)
**What**
1. Background - tabs component visual tests are flaky
2. What did you do - added ignore regions in code and created a ticket to review when applitools provide a fix: https://nidigitalsolutions.jira.com/browse/PPDSC-2520
3. What does the reviewers should expect - tabs component visual tests should consistently pass
**Before:**
**After:**
> fix(PPDSC-2513): add ignore regions to tabs tests

- site/pages/components/accordion.tsx
- site/pages/components/menu.tsx
- site/pages/components/tabs.tsx
PPDSC-2553
**What**
Copy updates to the Accordion component page
Copy updates to the Menu component page
Copy updates to the Tabs component page
**Before:**
**After:**
> docs(PPDSC-2553): update accordion docs

- site/pages/theme/presets/style-presets.tsx
- site/pages/theme/presets/transition-presets.tsx
- site/pages/theme/presets/typography-presets.tsx
PPDSC-2548
**What**
Content update from Tom's edits
Updated text from: https://docs.google.com/document/d/1ygayWr9V7txO66NDLtRWI7a6qYlENV8isTp2h8ZMHMw/edit?usp=sharing
Text to match doc
**Before:**
**After:**
> docs(PPDSC-2548): update content

- site/pages/about/introduction.tsx
PPDSC-2544
**What**
Update copy on About Introduction page
**Before:**
**After:**
> docs(PPDSC-2544): update about introduction

- src/banner/__tests__/banner.stories.tsx
- src/test/storybook-comps.tsx
PPDSC-2483
**What**
Updated Storybook scenarios for Banner component following the new layout based on the designs.
https://www.figma.com/file/phmWaRMlkssTtbv88pPVDl/NewsKit---Storybook-Project---Feedback-and-Status?node-id=1%3A6
**Before:**
**After:**
> docs(PPDSC-2483): update Banner storybook scenarios

- site/components/table-of-contents/table-of-contents.tsx
- site/pages/_app.tsx
- src/instrumentation/types.ts
PPDSC-2323
**What**
1. Background - to track scroll depths on components pages
2. What did you do - added fireEvent every time a section is in viewport
**Before:**
**After:**
> docs(PPDSC-2323): add event tracking to toc

- .circleci/config.yml
[PPDSC-2500](https://nidigitalsolutions.jira.com/browse/PPDSC-2500)
**What**
1. Background - main pipeline failing as stories.json not available
2. What did you do - e2e tests must run after storybook build so that stories.json is available
3. What does the reviewers should expect - main pipeline passes
**Before:**
**After:**
> fix(PPDSC-2500): fix pipeline deps

- .circleci/config.yml
[PPDSC-XXXX](https://nidigitalsolutions.jira.com/browse/PPDSC-2607)
**What**
**Before:**
**After:**
> chore(PPDSC-2607): add missing job to main workflow

- .circleci/config.yml
[PPDSC-2607](https://nidigitalsolutions.jira.com/browse/PPDSC-2607)
**What**
- Missing dependency for comps baseline update job
- Added missing dep
- Baselines should successfully update for comps
**Before:**
**After:**
> chore(PPDSC-2607): make storybook available for comp tests

- .circleci/config.yml
- scripts/check-baseline-updates.js
[PPDSC-2614](https://nidigitalsolutions.jira.com/browse/PPDSC-2614)
**What**
- Simplify code for checking if Percy baseline updates are required to make code more maintainable
- Used the GitHub cli (installed by default on CircleCI images) to fetch the branch name rather than the api
- No changes to pipeline behaviour
**Before:**
**After:**
> chore(PPDSC-2614): simplify fetching branch name for merge commit

- site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap
- site/components/svg-previewer/__tests__/__snapshots__/svg-previewer.test.tsx.snap
- src/base-switch/styled.tsx
- src/checkbox/__tests__/__snapshots__/checkbox.test.tsx.snap
- src/fieldset/__tests__/__snapshots__/fieldset.test.tsx.snap
- src/form/__tests__/__snapshots__/form.test.tsx.snap
- src/radio-button/__tests__/__snapshots__/radio-button.test.tsx.snap
- src/radio-button/__tests__/radio-button.stories.tsx
- src/switch/__tests__/__snapshots__/switch.test.tsx.snap
PPDSC-2633
**What**
1. Background - text was not cropping when bigger typography preset was used
2. What did you do- added withCrop on the styled span, this seems to have fixed the problem when i add a bigger font now it aligns
**Before:**
**After:**
> fix(PPDSE-2633): fix-ppdse-2633 added noCrop

- .circleci/config.yml
PPDSC-0000
**What**
**Before:**
**After:**
> chore(xxxx-0000): remove staging env

- lib/codemod/README.md
- lib/codemod/package.json
- lib/codemod/src/utils/__tests__/add-prop.test.js
- lib/codemod/src/utils/add-prop.js
- lib/codemod/src/v7.0.0/__tests__/all-default-styles.test.js
- lib/codemod/src/v7.0.0/__tests__/audio-player-default-styles.test.js
- lib/codemod/src/v7.0.0/all-default-styles.js
- lib/codemod/src/v7.0.0/audio-player-default-styles.js
- lib/codemod/yarn.lock
- package.json
- src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
- src/audio-player-composable/components/play-pause-button/play-pause-button.tsx
- src/audio-player-composable/components/time-display/defaults.ts
- src/audio-player-composable/components/volume-control/defaults.ts
- src/audio-player-composable/components/volume-control/style-presets.ts
- src/theme/__tests__/__snapshots__/theme.test.ts.snap
[PPDSC-2412](https://nidigitalsolutions.jira.com/browse/PPDSC-2412)
**What**
- Audio player styling changes
- Made styling changes
- Added codemod utility functions for updating nested props
- Added codemod to prevent visual changes from new version
- Added `...Old` style presets in order to override single style attributes. 
- Audio player should match _new_ styling by default
- Running codemods should apply _old_ styling. 
**Before:**
**After:**
[PPDSC-2412]: https://nidigitalsolutions.jira.com/browse/PPDSC-2412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> chore(PPDSC-2412): audio player styling changes

- site/utils/instrumentation.ts
PPDSC-2325
**What**
**Before:**
**After:**
> docs(PPDSC-2325): set tracking default object

- src/audio-player-composable/__tests__/__snapshots__/audio-player-composable.test.tsx.snap
- src/popover/__tests__/__snapshots__/popover.test.tsx.snap
- src/popover/style-presets.ts
- src/theme/__tests__/__snapshots__/theme.test.ts.snap
PPDSC-2774
**What**
1. Background - Popover styling component defaults changes
2. What did you do - Made styling changes
3. What does the reviewers should expect - Popover should match new styling by default
**Before:**
**After:**
> chore(PPDSC-2774): update Popover component defaults

- site/pages/components/consent.mdx
PPDSC-1966
**What**
1. Background - removed mentions as code support for AMP was removed some time ago
2. What did you do - deleted a line
**Before:**
**After:**
> docs(PPDSC-1966): remove amp mentions

- .circleci/config.yml
- README.md
PPDSC-2746
_NB 16/2/23: Because this depends on a DNS PROD change, it has to happen manually by a DevOps person (see https://github.com/newsuk/nuk-cdn), this PR should not be merged until new page https://newskit.co.uk/timestamp.html returns a date time instead of 404.
_17/2/23: I have just retested and https://newskit.co.uk/timestamp.html now returns the datetime of the last S3 prod deploy; whereas yesterday it was returning 404, so it must have been deployed to prod since I last checked, So, IS now safe to merge._
**What**
1. Background - final step in getting off of k8s
2. What did you do - circleci changes
3. What does the reviewers should expect - below tests to work
**Before:**
**After:** …
> ci(PPDSC-2746): migrate prod docs from k8s to s3

- src/text-block/__tests__/text-block.stories.tsx
PPDSC-2821
**What**
1. Background - updating Storybook scenarios
2. What did you do - updated TextBlock scenarios
3. What does the reviewers should expect - new TextBlock scenarios in storybook
**Before:**
**After:**
> docs(PPDSC-2821): update TextBlock component storybook scenarios

- site/pages/components/image.tsx
PPDSC-2845
**What**
1. Background - the image page is jumping when switching between light and dark theme
2. What did you do - the reason for jumping is that the image is 100% and has a ratio of 3:2 by default. When changing the theme the playground is removed and added to the dom, which causes the Image component to change its size. Adding a fixed height on the playground makes it stable.
**Before:**
**After:**
> docs(PPDSC-2845): update image playground

- .circleci/config.yml
PPDSC-XXXX
**What**
Updated channel for Ci notifications
**Before:**
**After:**
> ci(PPDSC-0000): updating channel for ci notifycations

- src/inline-message/__tests__/inline-message.stories.tsx
PPDSC-2800
**What**
**Before:**
**After:**
> docs(PPDSC-2800) inline-message-comp-update

- site/pages/components/layer.tsx
- src/layer/__tests__/layer.stories.tsx
PPDSC-2802
Using the [designs](https://www.figma.com/file/WnhT6FhgmZQbQVWYCW8w8Q/NewsKit---Storybook-Project---Utilities?node-id=2471%3A52421&t=reXlrvIrFqjub52L-0) update the storybook pages for the Layer component.
**Before:**
**After:**
> docs/PPDSC-2802: layer scenarios

- README.md
- site/components/component-api/common-logical-props.tsx
- site/components/component-api/component-api.tsx
- site/pages/components/pagination.tsx
PPDSC-2872 fresh PR
**What**
**Before:**
**After:**
> docs(PPDSC-2872): pagination documentation for defaults & customisations

- cypress/site/percy/fullpage-snapshots.cy.js
- site/components/homepage/whats-new/whats-new.tsx
#747
**What**
**Before:**
**After:**
> fix(747): hide version on home page

- site/pages/_app.tsx
- src/newskit-provider/__tests__/__snapshots__/newskitprovider.test.tsx.snap
- src/newskit-provider/__tests__/newskitprovider.test.tsx
- src/newskit-provider/context.tsx
- src/newskit-provider/newskit-provider.tsx
- src/test/__tests__/test-utils.test.ts
- src/test/test-framework-setup.ts
- src/theme/emotion.tsx
- src/utils/with-own-theme.tsx
closes #751
**What**
Add optimisation to with-own-theme to speed up re-rendering of components (including Drawer).
**Before:**
**After:**
> feat(751): add optimisation to with-own-theme

- package.json
- src/selection-list/__tests__/__snapshots__/selection-list.test.tsx.snap
- src/selection-list/selection-list-option.tsx
- yarn.lock
closes #727 
**What**
**Before:**
**After:**
> ci(727): upgrade axe-core

- .circleci/config.yml
closes #866
**What**
**Before:**
**After:**
> ci(866): pin create-next-app version

- cypress/site/percy/fullpage-snapshots.cy.js
- scripts/generate-a11y-tests-web.ts
- site/components/homepage/hero/hero-interactive-elements.tsx
- site/components/homepage/whats-new/whats-new.tsx
closes #795
**What**
1. Background - automated a11y tests fails on website homepage
2. What did you do - aria-hidden around decorative components
**Before:**
**After:**
> fix(795): automated a11y tests fails on website homepage

- src/icons/__tests__/progress-indicator.stories.tsx
closes #720 
**What**
**Before:**
**After:**
> docs(720): add progress indicator story

- package.json
- scripts/build-package-json-support.js
- scripts/build-package-json.js
- src/__tests__/__snapshots__/package.test.ts.snap
- src/__tests__/package.test.ts
- src/icons/__tests__/progress-indicator.stories.tsx
closes #871
**What**
1. Background - as a reminder to devs to keep dependenciesNotToBeIncluded up-to-date
2. What did you do - add test
3. What does the reviewers should expect - snapshot test to fail if/when package.json changes
**Before:**
**After:**
> chore(871): snapshot test package.json

- .circleci/config.yml
closes #824
**What**
1. Background - run percy tests in parallel, for that I changed tasks dependencies.
**Before:**
**After:**
> chore(824): run percy in parallel

- .storybook/preview.js
closes #000
**What**
**Before:**
**After:**
> chore(843): remove empty include option in skip-percy-tests

- site/pages/theme/presets/typography-presets.tsx
closes #900
**What**
**Before:**
**After:**
> docs(900): fix typography docs

- src/tealium/__tests__/__snapshots__/tealium.test.tsx.snap
- src/tealium/__tests__/tealium.test.tsx
- src/tealium/tealium.tsx
- src/utils/__tests__/__snapshots__/render-scripts.test.tsx.snap
- src/utils/__tests__/render-scripts.test.tsx
- src/utils/render-scripts.tsx
https://nidigitalsolutions.jira.com/browse/TMR-1282
**What**
1. Background - why this is needed - We are using a Content-Security-Policy in Next.js that stops 3rd party scripts running unless we specify them. To enable Newskit Tealium component to work we need to be able to add a nonce attribute to the inline script.
2. What did you do - added optional nonce prop to Tealium script
**Before:**
**After:**
> feat(TMR-1285): nonce prop to Tealium component
