src/banner/__tests__/banner.stories.tsx, src/drawer/__tests__/drawer-layouts.stories.tsx, src/form/__tests__/form-input.stories.tsx, src/menu/__tests__/menu.stories.tsx, src/modal/__tests__/modal-layouts.stories.tsx, src/modal/__tests__/modal.stories.tsx, src/structured-list/__tests__/structured-list.stories.tsx, src/toast/__tests__/toast.stories.tsx
[PPDSC-2105](https://nidigitalsolutions.jira.com/browse/PPDSC-2105)
**What**
1. Background: Some component stories specify a11y rules to be disabled when running cypress-axe tests. Some of these components are now compliant and the disabled rules can be re-enabled.  
2. Re-enabled any unnecessarily disabled rules in the tests.
* Run `accessibilty.spec.ts` and all tests should still pass despite fewer disabled rules.
=> fix(PPDSC-2105): remove unnecessarily disabled a11y rules in cmp tests

package.json, yarn.lock
[PPDSC-2104](https://nidigitalsolutions.jira.com/browse/PPDSC-2104)
**What**
1. Background: `package.json` for local next app being generated in the wrong location after upgrading to 12.1.
2. Increase next version to 12.1.1, which includes a fix for this behaviour. 
=> fix(PPDSC-2104): increase next version to >12.1.1

src/base-switch/base-switch.tsx, src/checkbox/__tests__/checkbox.test.tsx
PPDSC-2134
**What**
The consumers couldn't override the `data-testid` prop so we moved the default one above the `{...restProps}`. This way it can be overridden if necessary. 
=> fix(PPDSC-2134): make BaseSwitch data-testid overridable

package.json, yarn.lock
PPDSC-2072
**What**
To enable quicker debugging of issue in Applitools this enables the log flag so we get extra information if the CircleCi console. This can then be downloaded and sent to Applitools.
2. Enables the Applitools log flag. I also update the Applitools packages
3. Extra log information inside the CicrleCi console for the jobs.
**Before:**
**After:**
=> feat(PPDSC-2072): enable applitools logs

.circleci/config.yml
PPDSC-2160
**What**
I broke the NewsKit package, so I am fixing it.
move back to the main folder, so the publishment can happen correctly and the dist folder can be found.
**Before:**
**After:**
=> fix(PPDSC-2160): back to newskit folder

src/audio-player-composable/__tests__/audio-player-composable.test.tsx, src/audio-player-composable/__tests__/utils.test.tsx, src/audio-player-composable/components/seek-bar/utils.ts
PPDSC-2047
**What**
1. When user moves the seekbar curser manually multiple disparate buffered sections can exist. However these seem to switch to the mirror opposite to what there where when you stop moving the curser.
2. It was agreed to make it act more like the buffer on Youtube. You now only see the first buffer closet to the curser.
3. You should not see multiple buffers. Buffer will be by the curser though its size depends on what is returned by the audio elements buffer property (so if can fluctuate in size).
**Before:**
**After:**
=> fix(PPDSC-2047): Resolve gaps in buffering seekbar by refactoring formatTrackData

site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, src/typography/__tests__/__snapshots__/paragraph.test.tsx.snap, src/typography/__tests__/paragraph.stories.tsx, src/typography/__tests__/paragraph.test.tsx, src/typography/paragraph/paragraph.tsx
PPDSC-2203
**What**
1. Background - drop-cap on the paragraph component is broken when you use no-text only children like `text <b>other</b>` since for React treads that as multiple children
2. What did you do - 
2.1. - Updated code so that handles multiple children, and  adjusted the ScreenOnly content, to wrap only first word instead of the whole paragraph text
2.2. - When the first child is not a text it will not show the drop-cap.
2.3. - Added support for React.Fragment
4. What does the reviewers should expect
**Before:**
**After:**
=> fix(PPDSC-2203): handling non text children in Paragraph

src/accordion/__tests__/accordion.stories.tsx, src/button/__tests__/button.stories.tsx, src/checkbox/__tests__/checkbox.stories.tsx, src/icon-button/__tests__/icon-button.stories.tsx, src/link/__tests__/link.stories.tsx, src/menu/__tests__/menu.stories.tsx, src/radio-button/__tests__/radio-button.stories.tsx, src/select/__tests__/select.stories.tsx, src/slider/__tests__/slider.stories.tsx, src/switch/__tests__/switch.stories.tsx, src/tabs/__tests__/tabs.stories.tsx, src/tag/__tests__/tag.stories.tsx, src/text-field/__tests__/text-field.stories.tsx
PPDSC-2151
**What**
1. Outline property has been added to components. Need to show uses how they can customise this using overrides.
2. Adds new outline overrides stories to storybook.
3. Components that use outline property have example of outline overrides.
**Before:**
**After:**
=> feat(PPDSC-2151): add outline override examples

src/popover/__tests__/popover.stories.tsx, src/popover/__tests__/popover.test.tsx, src/popover/popover.tsx, src/popover/types.ts
PPDSC-2226
**What**
1. Background - why this is needed - Requested functionality for Audio Player requires change to Popover so when you click outside of popover or press esc the popover closes. 
2. What did you do - Added a new prop called `enableDismiss` that when set to true enables the above functionality. Original idea was to have to props so that clicking outside Popover or using esc key could be enables separately. However we are using the floating-ui library where this functionality comes as a package. 
3. What should the reviewers expect - When  `enableDismiss` set to true you can click outside of popover or press esc and popover will close
**Before:**
**After:**
=> feat(PPDSC-2226): functionality to dismiss popover

.circleci/config.yml
[PPDSC-2273](https://nidigitalsolutions.jira.com/browse/PPDSC-2273)
**What**
1. Background - applitools issues are hard to debug
2. What did you do 
- Use built-in CircleCI env variables to override default Applitools batchname with useful info.
- Make sure the curl request to close Applitools batches is always sent (for docs and components). At the moment the request is not sent if any tests in the suite, so the batch would remain open. Subsequent pipeline runs for the same commit would therefore add more tests to the same batch, rather than creating a new batch. This means that we cannot remove the global 'auto close batches' setting. Currently this is what closes our batches (and is also the reason why our batches are randomly split sometimes). …
=> feat(PPDSC-2273): add pr and job urls to applitools batch name

site/components/__tests__/__snapshots__/site-header.test.tsx.snap, site/components/component-api/__tests__/__snapshots__/component-api.test.tsx.snap, site/components/sidebar/__tests__/__snapshots__/sidebar-navigation.test.tsx.snap, site/components/sidebar/__tests__/__snapshots__/sidebar.test.tsx.snap, site/components/site-header.tsx, site/components/table/__tests__/__snapshots__/table.test.tsx.snap, site/components/tabs-with-table/__tests__/__snapshots__/tabs-with-table.test.tsx.snap, site/components/tools/__tests__/__snapshots__/svg-previewer.test.tsx.snap, site/theme/__tests__/__snapshots__/doc-theme.test.ts.snap, site/theme/typography-presets.json
PPDSC-2392
**What**
The `utilityButton020` typography preset was deleted incorrectly in the update theme task #345 😬 
This PR reverts the deleted typography preset.
Also as addition to this, on LG 1024px viewport screen the theme switch button is pushed out of the screen because of the #337 updates. This is now handled as well.
**Before:**
**After:**
=> fix(PPDSC-2392): revert utilityButton020 typography preset

.eslintrc.js, site/components/__tests__/__snapshots__/site-header.test.tsx.snap, site/components/menu-collapsible/menu-collapsible.tsx, site/components/sidebar/__tests__/__snapshots__/sidebar-navigation.test.tsx.snap, site/components/sidebar/sidebar-navigation.tsx, site/components/site-header.tsx
PPDSC-2236
**What**
1. Background - when you move between pages it would turn to light mode first then dark, in site-header and sidebar
2. What did you do-wrapped `MenuItem` in `LinkNext`
3. What does the reviewers should expect- you can now navigate between pages in dark mode and the page will remain in dark mode.
**Before:**
**After:**
=> docs(PPDSC-2336): chore-ppdse-2336-added NextLink added to site

.circleci/config.yml
PPDSC-2404
**What**
1. Background - why this is needed, develop env deploy is broken
2. What did you do - added version back in for image name that pushed to ECS
3. What does the reviewers should expect - both ECS and flux should have version and has in the image name
=> build(PPDSC-2404): add version back into image name for dev deploy

src/consent/consent-settings-link.tsx
PPDSC-2280
**What**
1. Background - If you are on a page on the website that is not the homepage and  you click privacy policy link in the footer section it goes back to homepage and the privacy policy modal does not load. The ticket suggested that the href should be updated to whatever page the user is on when they click the pp modal. However I found this did not work.  I tried the below example
```
<LinkStandalone
{...props}
href="components/overview"
role="button"
```
this had some weird behaviour the pp modal would show but the page would then refresh and go to `"components/overview"` and the PP modal would disappear.
I found that the href being passed in the `LinkStandlone `component was the problem. I did some research and ended up adding  ` event.preventDefault();` this stops the …
=> chore(PPDSC-2280): chore-ppdse-2280-added prevent default

cypress/components/accessibility.spec.ts, e2e/index.tsx, e2e/tests.tsx, src/banner/__tests__/banner.stories.tsx, src/block/__tests__/block.stories.tsx
PPDSC-2136
**What**
1. Background - **we have to test the dark theme for accessibility (colour contrast)**
2. What did you do - **added a way of running the a11y tests in both light and dark theme.**
4. What does the reviewers should expect - **running the e2e tests, the a11y set of tests should include both light and dark theme and all tests should pass.**
Run locally `yarn e2e:build && yarn e2e:serve` and then in a separate terminal run `yarn e2e:comps` and start the a11y set of tests, or check if the CI e2e tests are ok. 
**Before:**
**After:**
=> chore(PPDSC-2136): add accessibility tests for newskit dark theme

.circleci/config.yml
PPDSC-2471
**What**
Updated `DOCKER_TAG` in `config.yml` file to differentiate a dev vs prod vs release builds.
We need this in order to fix the `approve_publish_docs_&_storybook` step and manually release docs and storybook from `main`. This is step one of the ticket. 
After this gets merged I will test the above step and if it works then I will open another PR for removing that manual step and enable docs deploy on every merge to main.
**Before:**
**After:**
=> ci(PPDSC-2471): update DOCKER_TAG to enable deploys from main

src/grid-layout/__tests__/utils.test.tsx, src/grid-layout/utils.ts
PPDSC-2494
**What**
1. Background - the sun is using templates for grid-layout areas which are without space, which breaks our component. for example, the code below will not work:
```js
const areasWithNoSpace = `
A
B
C
D`;
```
**Before:**
**After:**
=> fix(PPDSC-2494): fix grid-layout areas with no space

.storybook/preview-head.html
[PPDSC-2480](https://nidigitalsolutions.jira.com/browse/PPDSC-2480)
**What**
Font file not loading for Virgin so incorrect font displaying in Storybook theme checker
- Old Montserrat font link was invalid
- Instead of hardcoding the new one, add a link element to load a stylesheet that imports the fonts
- This matches what Virgin do on their site
Virgin fonts display correctly in theme checker
**Before:**
**After:**
=> fix(PPDSC-2480): load correct font urls

site/pages/getting-started/code/engineering-overview.tsx, site/pages/getting-started/code/engineering-quickstart.tsx, site/pages/getting-started/code/instrumentation.tsx, site/pages/getting-started/design/design-overview.tsx, site/pages/getting-started/overview.tsx, site/routes.ts
PPDSC-2545
**What**
1. Copy changes
2. Updated copy in guides pages
**Before:**
**After:**
=> docs(PPDSC-2545): copy updates to guide pages

package.json, site/components/component-api/common-logical-props.tsx, site/components/table/column-map.ts, site/pages/components/button.tsx, site/pages/components/checkbox.tsx, site/pages/components/form.tsx, site/pages/table-variants.tsx, site/templates/template-sections/__tests__/__snapshots__/accessibility-section.test.tsx.snap, site/templates/template-sections/accessibility-section.tsx, yarn.lock
PPDSC-XXXX
**What**
**Before:**
**After:**
=> docs:(PPDSC-2549) components content updates

site/pages/components/accordion.tsx, site/pages/components/audio-player.tsx, site/pages/components/flag.tsx, site/pages/components/modal.tsx
PPDSC-2627
**What**
**Before:**
**After:**
=> docs(PPDSC-2627) updated overrides in doc sites

.circleci/config.yml
PPDSC-2614
**What**
- `main` job to update percy baselines failing
- make sure `gh` cli is initialized
- percy baselines should update when required
**Before:**
**After:**
[PPDSC-2614]: https://nidigitalsolutions.jira.com/browse/PPDSC-2614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(PPDSC-2614): make sure gh cli initialized

site/utils/google-sheet/__tests__/get-sheets.test.ts, site/utils/google-sheet/get-sheets.ts, src/link/__tests__/utils.test.tsx, src/link/utils.tsx, src/test/__tests__/test-utils.test.ts
PPDSC-2643
**What**
1. Background - under src, get-sheets, utils and test-utils are missing a few tests
2. What did you do - add more unit tests
**Before:**
**After:**
[PPDSC-2643]: https://nidigitalsolutions.jira.com/browse/PPDSC-2643?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(PPDSC-2643): add missing unit tests for getSheets

site/components/playground/index.tsx, site/components/playground/knobs/input-knob.tsx, site/components/playground/knobs/multichoice-knob.tsx, site/pages/_document.tsx, site/routes.ts
PPDSC-2325
**What**
1. Background - we need a way to track playground
2. What did you do - added instrumentation provider and fireEvents on knobs
**Before:**
**After:**
[PPDSC-2325]: https://nidigitalsolutions.jira.com/browse/PPDSC-2325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(PPDSC-2325): improve tracking in playground section

site/components/media-list/media-list.tsx, site/pages/components/overview.tsx
PPDSC-2650
- Checked with Mike to remove the extra cell on smaller breakpoints. 
**Before:**
**After:**
[PPDSC-2650]: https://nidigitalsolutions.jira.com/browse/PPDSC-2650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs(PPDSC-2650): react error on components overview

site/pages/about/roadmap.tsx
PPDSC-2693
On the [NewsKit.co.uk roadmap page](https://newskit.co.uk/about/roadmap/#current) this text: “The roadmap is a living document, and it is likely that priorities will change” is black instead of white when the page is viewed in dark mode
**Before:**
**After:**
=> docs(PPDSC-2693): add stylePreset to TextBlock

src/breadcrumbs/__tests__/__snapshots__/breadcrumbs.test.tsx.snap, src/breadcrumbs/__tests__/breadcrumbs.stories.tsx, src/breadcrumbs/defaults.ts, src/theme/__tests__/__snapshots__/theme.test.ts.snap
PPDSC-2696
The breadcrumb item currently has padding top and bottom (inherited from the Button). 
This needs to be removed. There already is a paddingInline: 'space000' but need the same for paddingBlock
**Before:**
**After:**
=> feat(PPDSC-2696): set default padding block to 'space000' for breadCrumbItem

.circleci/config.yml
PPDSC-2712
https://app.circleci.com/pipelines/github/newscorp-ghfb/newskit/5873/workflows/55be43c4-206e-4767-8c18-34a761856b01/jobs/123993 failed on “deploy_terraform_s3_dev” step due to “"Error pulling image newsuk/terraform:1.2.1: failed to register layer: Error processing tar file(exit status 1): write /usr/lib/x86_64-linux-gnu/libwebp.so.7.1.3: no space left on device... retrying image cache not found on this host, downloading newsuk/terraform:1.2.1"
Having read this: [Disk space limited in docker image](https://discuss.circleci.com/t/disk-space-limited-in-docker-image/38896)  using resource_class: large may solve the issue.
**Before:**
**After:**
=> fix(PPDSC-2712): circle remote docker has no space left

src/icon-button/__tests__/icon-button.stories.tsx
PPDSC-2708
**What**
Updated IconButton component storybook scenarios
**Before:**
**After:**
=> docs(PPDSC-2708): update IconButton component storybook scenarios

site/pages/components/structured-list.tsx, src/structured-list/__tests__/__snapshots__/structured-list.test.tsx.snap, src/structured-list/__tests__/structured-list.stories.tsx, src/structured-list/__tests__/structured-list.test.tsx, src/structured-list/structured-list-item.tsx, src/structured-list/types.ts
https://github.com/newscorp-ghfb/newskit/issues/690
**What**
1. Background - As a user, I would like to align the divider and content when there is only one cell in StructuredList so there is no extra padding/margin
2. What did you do - to avoid making a breaking change, I've added a prop to allow this to happen
3. What does the reviewers should expect - The rest of the scenarios should still work as expected. There is one extra scenario added to one cell.
**Before:**
**After:**
=> feat(ISSUE-4): add fullWidthSingleCell prop to structuredListCell

src/structured-list/__tests__/__snapshots__/structured-list.test.tsx.snap, src/structured-list/structured-list.tsx
[SCS-70](https://nidigitalsolutions.jira.com/browse/SCS-70)
**What**
1. Background - #709 
2. What did you do - wrapped the Divider elements in list items 
3. What does the reviewers should expect - no a11y errors even if the list has a `role="list"`
**Before:**
**After:**
[SCS-70]: https://nidigitalsolutions.jira.com/browse/SCS-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(SCS-70): structured-list with divider a11y issue

.github/ISSUE_TEMPLATE/a11y_investigation.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/spike.md, .github/ISSUE_TEMPLATE/story.md, .github/ISSUE_TEMPLATE/task.md, .github/PULL_REQUEST_TEMPLATE.md, .github/release.yml, githooks/commitmsg.js, githooks/constants.js, githooks/preparecommitmsg.js
#775
**What**
1. Background - why this is needed to support our move to GitHub issues
2. What did you do? updated the git commit hook, PR template and Issues Templates. Bonus fix that was preventing docs be separate in release notes.
3. What the reviewers should expect? changes to GitHub files
=> chore(775): move to GitHub issues

src/modal/__tests__/modal.stories.tsx
#809 
**What**
Button alignment mismatching on Custom restore focus scenario - Modal Component Storybook Scenarios
**Before:**
**After:**
=> fix(809): Button alignment mismatching on Custom restore focus - Modal scenario

src/standfirst/__tests__/standfirst.stories.tsx
closes  #723 
**What**
**Before:**
**After:**
=> docs(723): Standfirst Storybook Enhancement

src/form/__tests__/form.test.tsx, src/form/form-entry.tsx, src/form/form-input.tsx, src/text-field/types.ts
Empty textfields have validation in forms even when they are optional:
This ticket updates the logic so when the text field input is not required and empty no validation visuals are visible.
Before:
After:
**What**
**Before:**
**After:**
=> feat(TMR-1134): refactor form input logic

src/__tests__/__snapshots__/package.test.ts.snap, src/__tests__/package.test.ts
closes #896
**What**
**Before:**
**After:**
=> fix(896): fix package.json test when bump version

src/select/__tests__/__snapshots__/select.test.tsx.snap, src/select/__tests__/select.stories.tsx, src/select/__tests__/select.test.tsx, src/select/select.tsx, src/select/types.ts
**What**
https://github.com/newscorp-ghfb/NewsKit/assets/16742525/dfe693e9-3443-40e0-a622-9808de43ddf4
https://github.com/newscorp-ghfb/NewsKit/assets/16742525/819306a8-9ac4-4393-a7ae-7b8e04d8d61e
**Before:**
**After:**
=> feat(898): Select panel position

.circleci/config.yml, site/pages/about/roadmap.tsx, site/pages/components/community/community-index.tsx, site/pages/index.tsx
closes #919
**What**
1. Background - missing google sheets file and old version of nodejs are breaking our pipeline
2. What did you do - updated nodejs on circleci and removed google sheets API, replacing it with static information
3. What does the reviewers should expect - everything should look exactly the same
**Before:**
**After:**
=> ci(919): update node version in circleci

src/audio-player-composable/audio-player-composable.tsx
Renamed branch, original PR: #929
closes #921
Currently the AudioPlayerComposable component has a problem with live streaming, where it infinitely loops the first second of audio if rendered in the Firefox browser. The component seems to work fine in Chrome. The reason it doesn't work in Firefox comes down to how the two browsers handle the onDurationChange event, or more specifically the value that is applied to `duration` for unbounded streams.
In Chrome the browser assigns `duration` the value of `Infinity`, which is in accordance with the [HTML spec](https://html.spec.whatwg.org/multipage/media.html#dom-media-duration-dev) (see also [MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/duration)), but in Firefox (for reasons I haven't been able to discover) the …
=> fix: AudioPlayerComposable - Prevent loop in firefox
